
spring:
  datasource:
    url: jdbc:mysql://${db.host}:3306/four_cut_photos_map?useUnicode=true&characterEncoding=utf8&serverTimeZone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${db.user}
    password: ${db.password}

  # todo 운영 데이터베이스 연결
  jpa:
    hibernate:
      ddl-auto: none # 운영중에서는 creat, create-drop, update 사용하면 안됨

  # redis 설정
  redis:
    host: 49.50.175.194
    port: 6379
# 운영 환경의 경우 요청이 많았을 경우 디버깅의 경우에 로그가 너무 많아 디스크 용량이 부족할 수 있어서 "info"로 변경
logging:
  level:
    com.app: info # todo 패키지 수정