spring:
  datasource:
    url: jdbc:mariadb://${testDbIp:localhost}:3306/four_cut_photos_map_test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: ${testDbId:root}
    password: ${testDbPw:0114}

  jpa:
#    database: mysql   # 추가 해준 부분
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect # 추가 해준 부분
    hibernate:
      ddl-auto: create

  sql:
    init:
      mode: never # 테스트 코드에서는 data.sql 적용막기 (팀원들이랑 의논해야할듯)