spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  sql:
    init:
      mode: never # 테스트 코드에서는 data.sql 적용막기 (팀원들이랑 의논해야할듯)
