-- insert into memberTitle (create_date, modify_date, name) values(NOW(), NOW(), '뉴비');
-- insert into memberTitle (create_date, modify_date, name) values(NOW(), NOW(), '포토부스 리뷰어'); -- 리뷰
-- insert into memberTitle (create_date, modify_date, name) values(NOW(), NOW(), '포토부스 전문가'); -- 방문횟수

INSERT INTO SHOP(create_date, modify_date, road_address_name, longitude, latitude, place_name, brand)VALUES (NOW(), NOW(), '서울 성동구 서울숲2길 48', 127.043851506853, 37.5461761379704, '인생네컷 서울숲노가리마트로드점', '인생네컷');
INSERT INTO SHOP(create_date, modify_date, road_address_name,longitude, latitude, place_name, brand) VALUES(NOW(), NOW(), '서울 성동구 서울숲2길 17-2',127.04073790685483, 37.547177362006806, '포토이즘박스 성수점', '포토이즘박스');
INSERT INTO SHOP(create_date, modify_date, road_address_name,longitude, latitude, place_name, brand) VALUES(NOW(), NOW(), '서울 성동구 서울숲4길 13',127.042449120263, 37.5475677927281, '인생네컷 카페성수로드점', '인생네컷');
INSERT INTO SHOP(create_date, modify_date, road_address_name,longitude, latitude, place_name, brand) VALUES(NOW(), NOW(), '서울 성동구 서울숲2길 45',127.043600450617, 37.5464465306291, '하루필름 서울숲점', '하루필름');
INSERT INTO SHOP(create_date, modify_date, road_address_name,longitude, latitude, place_name, brand) VALUES(NOW(), NOW(), '서울 성동구 서울숲4길 20',127.043010183447, 37.547189170196, '인생네컷 서울숲점', '인생네컷');
INSERT INTO SHOP(create_date, modify_date, road_address_name,longitude, latitude, place_name, brand) VALUES(NOW(), NOW(), '서울 성동구 서울숲4길 23-1',127.043634812377, 37.5471565050697, '픽닷', '픽닷');
INSERT INTO SHOP(create_date, modify_date, road_address_name,longitude, latitude, place_name, brand) VALUES(NOW(), NOW(), '충남 천안시 서북구 원두정2길 21',127.135473811813, 36.8322023787607, '인생네컷 충남천안두정먹거리공원점', '인생네컷');
INSERT INTO SHOP(create_date, modify_date, road_address_name,longitude, latitude, place_name, brand) VALUES(NOW(), NOW(), '충남 천안시 동남구 먹거리10길 14',127.155328, 36.817782, '하루필름 천안점', '하루필름');
INSERT INTO SHOP(create_date, modify_date, road_address_name,longitude, latitude, place_name, brand) VALUES(NOW(), NOW(), '충남 천안시 서북구 원두정2길 21',127.135473811813, 36.8322023787607, '포토이즘박스 두정점', '포토이즘박스');
INSERT INTO SHOP(create_date, modify_date, road_address_name,longitude, latitude, place_name, brand) VALUES(NOW(), NOW(), '충남 천안시 동남구 먹거리11길 28',127.155596175371, 36.8181132541858, '포토이즘컬러드 천안신부점', '포토이즘박스');


-- 칭호
INSERT INTO MEMBER_TITLE(create_date, modify_date, name, content) VALUES (NOW(), NOW(), '뉴비', '네컷지도 가입');
INSERT INTO MEMBER_TITLE(create_date, modify_date, name, content) VALUES (NOW(), NOW(), '리뷰 첫 걸음', '리뷰 1회 누적');
INSERT INTO MEMBER_TITLE(create_date, modify_date, name, content) VALUES (NOW(), NOW(), '리뷰 홀릭', '리뷰 5회 누적');
INSERT INTO MEMBER_TITLE(create_date, modify_date, name, content) VALUES (NOW(), NOW(), '찜 첫 걸음', '찜 1회 누적');
INSERT INTO MEMBER_TITLE(create_date, modify_date, name, content) VALUES (NOW(), NOW(), '찜 홀릭', '찜 5회 누적');

INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());

-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
--
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
--
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
--
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
--
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
--
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
--
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
--
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
--
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
-- INSERT INTO MEMBER(create_date, modify_date) VALUES (NOW(), NOW());
